// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function BootstrapWorkspace():Promise<api.WorkspaceBootstrapResponse>;

export function ClearRunHistory(arg1:string):Promise<api.RunHistoryActionResponse>;

export function Connect(arg1:api.ConnectionRequest):Promise<api.ConnectionResponse>;

export function CreateWorkspace(arg1:string):Promise<api.WorkspaceBootstrapResponse>;

export function DeleteRunHistory(arg1:string,arg2:string):Promise<api.RunHistoryActionResponse>;

export function DeleteWorkspace(arg1:string):Promise<api.WorkspaceBootstrapResponse>;

export function Disconnect():Promise<api.ConnectionStatusResponse>;

export function GetConnectionStatus():Promise<api.ConnectionStatusResponse>;

export function GetRunHistory(arg1:string,arg2:string):Promise<api.RunHistoryResponse>;

export function ImportLocalScenario():Promise<api.ScenarioFileResponse>;

export function ListBundledScenarios():Promise<api.ScenarioListResponse>;

export function ListLocalScenarios():Promise<api.ScenarioListResponse>;

export function ListRunHistory(arg1:string):Promise<api.RunHistoryListResponse>;

export function LoadBundledScenario(arg1:string):Promise<api.ScenarioResponse>;

export function LoadLocalScenario(arg1:string):Promise<api.ScenarioResponse>;

export function RemoveLocalScenario(arg1:string):Promise<api.ScenarioFileResponse>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<api.WorkspaceBootstrapResponse>;

export function RetryWorkspacePersistence(arg1:boolean):Promise<api.WorkspaceBootstrapResponse>;

export function SaveLocalScenario(arg1:string,arg2:api.ScenarioDraft):Promise<api.ScenarioFileResponse>;

export function SaveScenarioAs(arg1:api.ScenarioDraft):Promise<api.ScenarioFileResponse>;

export function SetActiveWorkspace(arg1:string):Promise<api.WorkspaceBootstrapResponse>;

export function SetWorkspaceSelectedScenario(arg1:api.WorkspaceSelectionRequest):Promise<api.WorkspaceActionResponse>;

export function StartRun(arg1:api.RunRequest):Promise<api.RunStartResponse>;

export function StopRun(arg1:string):Promise<api.RunControlResponse>;
