// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Connect(arg1:api.ConnectionRequest):Promise<api.ConnectionResponse>;

export function Disconnect():Promise<api.ConnectionStatusResponse>;

export function GetConnectionStatus():Promise<api.ConnectionStatusResponse>;

export function Run(arg1:api.RunRequest):Promise<api.RunResponse>;
