// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Connect(arg1:api.ConnectionRequest):Promise<api.ConnectionResponse>;

export function Disconnect():Promise<api.ConnectionStatusResponse>;

export function GetConnectionStatus():Promise<api.ConnectionStatusResponse>;

export function ImportLocalScenario():Promise<api.ScenarioFileResponse>;

export function ListBundledScenarios():Promise<api.ScenarioListResponse>;

export function ListLocalScenarios():Promise<api.ScenarioListResponse>;

export function LoadBundledScenario(arg1:string):Promise<api.ScenarioResponse>;

export function LoadLocalScenario(arg1:string):Promise<api.ScenarioResponse>;

export function SaveLocalScenario(arg1:string,arg2:api.ScenarioDraft):Promise<api.ScenarioFileResponse>;

export function SaveScenarioAs(arg1:api.ScenarioDraft):Promise<api.ScenarioFileResponse>;

export function StartRun(arg1:api.RunRequest):Promise<api.RunStartResponse>;

export function StopRun(arg1:string):Promise<api.RunControlResponse>;
