// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function ListBundledScenarios() {
  return window['go']['main']['App']['ListBundledScenarios']();
}

export function LoadBundledScenario(arg1) {
  return window['go']['main']['App']['LoadBundledScenario'](arg1);
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}
