// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BootstrapWorkspace() {
  return window['go']['main']['App']['BootstrapWorkspace']();
}

export function ClearRunHistory(arg1) {
  return window['go']['main']['App']['ClearRunHistory'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteRunHistory(arg1, arg2) {
  return window['go']['main']['App']['DeleteRunHistory'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetRunHistory(arg1, arg2) {
  return window['go']['main']['App']['GetRunHistory'](arg1, arg2);
}

export function ImportLocalScenario() {
  return window['go']['main']['App']['ImportLocalScenario']();
}

export function ListBundledScenarios() {
  return window['go']['main']['App']['ListBundledScenarios']();
}

export function ListLocalScenarios() {
  return window['go']['main']['App']['ListLocalScenarios']();
}

export function ListRunHistory(arg1) {
  return window['go']['main']['App']['ListRunHistory'](arg1);
}

export function LoadBundledScenario(arg1) {
  return window['go']['main']['App']['LoadBundledScenario'](arg1);
}

export function LoadLocalScenario(arg1) {
  return window['go']['main']['App']['LoadLocalScenario'](arg1);
}

export function RemoveLocalScenario(arg1) {
  return window['go']['main']['App']['RemoveLocalScenario'](arg1);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function RetryWorkspacePersistence(arg1) {
  return window['go']['main']['App']['RetryWorkspacePersistence'](arg1);
}

export function SaveLocalScenario(arg1, arg2) {
  return window['go']['main']['App']['SaveLocalScenario'](arg1, arg2);
}

export function SaveScenarioAs(arg1) {
  return window['go']['main']['App']['SaveScenarioAs'](arg1);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetWorkspaceSelectedScenario(arg1) {
  return window['go']['main']['App']['SetWorkspaceSelectedScenario'](arg1);
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}
